version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      REDIS_URL: redis://redis:6379/0
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  celery_worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      REDIS_URL: redis://redis:6379/0
    command: celery -A celery_repo.celery_worker.celery_app worker --loglevel=info

  frontend:
    build:
      context: .
      dockerfile: mindmap/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000

volumes:
  mongo-data:
